import { Container, ThemeProvider, Box, Typography, createTheme, colors } from '@mui/material'


import React from 'react'

// const theme = createTheme({
//     palette: {

//         primary: {
//             main: colors.grey[500]
//         },
//     }
// })
const Home = () => {
    return (

        <Container maxWidth="md"  >
            <Box >
                <Typography variant="h1" align="center" className="home-intro">I'm Edgar</Typography>
                <Typography variant="subtitle1" align="center" className="intro-p">a programmer.</Typography>

                <Typography variant="h6" align='left'>Hello there,</Typography>
                <Typography variant="body1" align='center'>My name is Edgar. I am a Full Stack Web Developer.
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                    Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhsCurrently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs Currently residing in York, Pennsylvania. asbdiuash asdhaosdoaidjo asd asjidaohs iosh shia aihsihaih aihai aiahiaha ihdih e  ieieiei e e e ei e ieiie ei e eie ie ieie dcisxhs
                </Typography>
            </Box>
        </Container>



    )
}

export default Home
